### PR TITLE
pass through max_body_size to the HTTPServer

### LINKED ISSUE #2: Need passthrough for max_body_size
Need a way to pass a `max_body_size` to the HTTPServer constructor in the RestServer constructor.

### PR DESCRIPTION
**Pull request by dsschult**
Closes #2

### CODE REVIEW

**Comment by dsschult** [comment]
There aren't any server tests at all.  Maybe those should be added at some point?  Not sure if they should come in this PR, or as part of a separate one (larger effort).

**Comment by ric-evans** [comment]
> There aren't any `RestServer` tests at all. Maybe those should be added at some point? Not sure if they should come in this PR, or as part of a separate one (larger effort).

RestServer (unlike RestClient) is a pretty simple wrapper. So I don't think there's much to _unit_ test.

**Review by ric-evans — APPROVED** [review]

**Comment by dsschult** [comment]
True.  Would probably be more like an integration test.  Though those should be fast to run anyway, since it's mostly just asking if the server is alive under various circumstances.

**Review by blinkdog — APPROVED** [review]
LGTM

**Pull request merged**
