### PR TITLE
Updates for PyPI Publish [minor]

### PR DESCRIPTION
**Pull request by ric-evans**
closes https://github.com/WIPACrepo/rest-tools/issues/61

### CODE REVIEW

**Comment by ric-evans** [comment]
TODOs:
- fix mypy fail
- make `wipac-telemetry` optional

**Comment by ric-evans** [comment]
@dsschult I decided to move the unused integration tests to `examples/`. There are a total of 3 `assert`s between the two scripts

**Review by dsschult — COMMENTED** [review]
My biggest question is how we can share `.github/workflows/setup-and-release.yml`and similar between repos, or at least the bulk of it, so that we don't get copy/paste divergences.

**Comment by ric-evans** [comment]
> My biggest question is how we can share `.github/workflows/setup-and-release.yml`and similar between repos, or at least the bulk of it, so that we don't get copy/paste divergences.

I'm thinking the honor system is good enough, at least try to make `wipac-dev-tools` always up-to-date. I put this at the top of the file:
```
# For most recent version see:
# https://github.com/WIPACrepo/wipac-dev-tools/blob/main/.github/workflows/setup-and-release.yml
# Copy any updates to wipac-dev-tools.
```

We could actually make a GH action package like you mentioned last week. But, that's out of scope. I could do that as follow-up PRs, if you think it's needed.

**Comment by dsschult** [comment]
> > My biggest question is how we can share `.github/workflows/setup-and-release.yml`and similar between repos, or at least the bulk of it, so that we don't get copy/paste divergences.
> 
> I'm thinking the honor system is good enough, at least try to make `wipac-dev-tools` always up-to-date. I put this at the top of the file:
> 
> ```
> # For most recent version see:
> # https://github.com/WIPACrepo/wipac-dev-tools/blob/main/.github/workflows/setup-and-release.yml
> # Copy any updates to wipac-dev-tools.
> ```
> 
> We could actually make a GH action package like you mentioned last week. But, that's out of scope. I could do that as follow-up PRs, if you think it's needed.

I'm thinking the GH action package is the best way to do this, considering how many repos we want to apply this across.  But maybe @blinkdog thinks differently?

**Comment by ric-evans** [comment]
@dsschult @blinkdog let's spin this conversation off to https://github.com/WIPACrepo/wipac-dev-tools/issues/28

**Pull request merged**
